language: node_js
node_js:
  - "stable"

before_install:
  - cd web-components

script:
  - npm run test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  pushmi_pullyou: $pmpy
  local_dir: web-components/build
  on:
    branch:
      - master
      - devel
      - hwork2
      - /^hwork\d+$/
