language: node_js
node_js:
  - 'stable'

before_install:
  - cd exam_2

script:
  - npm run test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $pmpy
  local_dir: exam_2/build
  on:
    branch:
      - exam_2
