language: node_js
node_js:
  - 'stable'

script:
  - npm run test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $pmpy
  local_dir: build
  on:
    branch:
      - master
      - 2hw1
      - 2hw2
      - 2hw3
      - 2hw4
      - 2hw5
      - 2hw6
      - 2hw7
      - 2hw8
      - 2hw9
      - 2hw10
